// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CodeDomClass
{
    using System;
    
    
    public sealed class testClass
    {
        
        // Object value
        private double valueField;
        
        public testClass(double value)
        {
            this.valueField = value;
        }
        
        private double valueProperty
        {
            get
            {
                return this.valueField;
            }
        }
        
        public override string ToString()
        {
            return string.Format("Object value: {0}", this.valueProperty);
        }
    }
}
